### ISSUE TITLE
Did you get nodebb to work with your custom cas sso?

### ISSUE THREAD

**Issue by Abraham21** [ld000/nodebb-plugin-cas#1]
I am currently trying to use the nodebb-plugin-sso-oauth plugin to work with my apereo cas sso. I have endpoints set up to call. I am getting errors.

I hope you can help me out. Perhaps I can use this plugin if it works?

Thank you,
Abraham Yepremian

**Comment by ld000** [comment]
this plugin work for me, use it in my bbs.
